name: Python Script Scheduler
 
on:
  schedule:
    - cron: '0/15 * * * *'  # Runs every day at midnight UTC
 
jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
        
    - name: Install dependencies
      run: pip install requests 
      
    - name: Run Python script
      run: python CodeScanningAlerts.py
